// Generated by CoffeeScript 1.12.7
(function() {
  var process_priors, process_priors_hash;

  process_priors = ["ppLowest", "ppLow", "ppNormal", "ppHigh", "ppHighest"];

  process_priors_hash = [
    {
      val: "ppLowest",
      name: "Очень низкий",
      prior: 5
    }, {
      val: "ppLow",
      name: "Низкий",
      prior: 4
    }, {
      val: "ppNormal",
      name: "Нормальный",
      prior: 3
    }, {
      val: "ppHigh",
      name: "Высокий",
      prior: 2
    }, {
      val: "ppHighest",
      name: "Очень высокий",
      prior: 1
    }
  ];

}).call(this);

//# sourceMappingURL=classes.js.map
